language: python
python:
  - '3.6.9'

before_script:
  - pip install -r requirements.txt
  -  psql -c 'p1;' -U postgres
  - ALTER user postgres WITH PASSWORD '123';
  - ALTER ROLE postgres SET client_encoding TO 'utf8';
  - ALTER ROLE postgres SET default_transaction_isolation TO 'read committed';
  - ALTER ROLE postgres SET SET timezone TO 'UTC';
  - python manage.py makemigrations store register
  - python manage.py migrate


services:
  - postgresql

script:
  - python manage.py test