language: python
python:
  - '3.6.9'
addons:
  firefox: "49.0"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux32.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver


before_script:
  - pip install -r requirements.txt
  - psql -c 'CREATE DATABASE p1;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD '123';" -U postgres
  - python manage.py makemigrations store register
  - python manage.py migrate


services:
  - postgresql

script:
  - python manage.py test