language: python
python:
  - '3.6.9'

before_script:
  - pip install -r requirements.txt
  -  psql -c 'CREATE DATABASE p1;' -U postgres
  - psql -c "CREATE USER postgres ;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD '123';" -U postgres
  - python manage.py makemigrations store register
  - python manage.py migrate


services:
  - postgresql

script:
  - python manage.py test